# Generated by Django 4.2.1 on 2023-05-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_remove_schedule_tutor_schedule_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.tutor')),
            ],
        ),
    ]
