# Generated by Django 4.2.1 on 2023-05-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_subjecttutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttutor',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecttutor',
            name='tutor',
        ),
        migrations.AddField(
            model_name='subjecttutor',
            name='subject',
            field=models.ManyToManyField(to='college_app.subject', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='subjecttutor',
            name='tutor',
            field=models.ManyToManyField(to='college_app.tutor', verbose_name='Преподаватель'),
        ),
    ]
