# Generated by Django 4.2.1 on 2023-05-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0007_remove_subjecttutor_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.subject', verbose_name='Предметы'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.tutor', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.classtime', verbose_name='Время'),
        ),
    ]
