# Generated by Django 4.2.1 on 2023-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0009_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
