# Generated by Django 4.2.1 on 2023-05-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0010_grade_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеттер'},
        ),
        migrations.AlterModelOptions(
            name='classtime',
            options={'verbose_name': 'Сабақ уақыты', 'verbose_name_plural': 'Сабақ уақыты'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Аптаның күні', 'verbose_name_plural': 'Аптаның күні'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Баға', 'verbose_name_plural': 'Бағалар'},
        ),
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Топ', 'verbose_name_plural': 'Топтар'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Жаңалықтар', 'verbose_name_plural': 'Жаңалықтар'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Кесте', 'verbose_name_plural': 'Кестелер'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенттер'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Сабақ', 'verbose_name_plural': 'Сабақтар'},
        ),
        migrations.AlterModelOptions(
            name='subjecttutor',
            options={'verbose_name': 'Оқытушының мамандануы', 'verbose_name_plural': 'Оқытушылардың мамандануы'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Оқытушы', 'verbose_name_plural': 'Оқытушылар'},
        ),
    ]
